### ISSUE TITLE
Zwift Group/Event Chat

### ISSUE THREAD

**Issue by LTZGH** [SauceLLC/sauce4zwift#122]
**Describe the bug**
When riding in a Group event such as "AHDR Bacon Rolls", the group Chat disappears. Before the event and after the event finishes "Chat Module" functions as normal. I'm a regular ride leader and this has only started not functioning over the past week.

**To Reproduce**
Enter any group event and enable the 'Chat' module.

**Expected behavior**
No visible group chat in the module during the entire event.

**Screenshots**

**Desktop (please complete the following information):**
Windows 11 64
My system is updated to the most recent software and drivers on Windows, Nvidia, Zwift, and Sauce. I performed a clean uninstall of Sauce 1.1.6 and rebooted to a new install to troubleshoot with no success removing the bug.

**Additional context**
I've never had this issue prior.

**Comment by LTZGH** [comment]
Please reopen case: @mayfield  I can confirm the issue was not fixed for chat in group events

**Comment by mayfield** [comment]
> Please reopen case: @mayfield I can confirm the issue was not fixed for chat in group events

Fixed in source code.  A new release will be out in the next day or so that includes this.

**Comment by StuRimmer** [comment]
Hi, still not having chat in group rides! Works fine in free rides.
How do I get the above mentioned 'fix'?
Thanks,

**Comment by LTZGH** [comment]
I'm using Alpha version and if I restart whilst in the pen it's a good
workaround.

**Comment by StuRimmer** [comment]
I always restart when in the pen or open a fresh and still no chat..

**Comment by StuRimmer** [comment]
Oh just noticed I can change channel.. was on 'stable' but will give Alpha a go. Thanks @LTZGH

**Comment by LTZGH** [comment]
Have you tried the Alpha version instead of stable?

**Comment by LTZGH** [comment]
As a beacon for group events, I just went Alpha and it seemed to work with
a reset while in the pens.

**Comment by StuRimmer** [comment]
Just changed it and got the update. Notes say 'update for group ride chat' and so hopefully it'll work!
Cheers for your help. Will try over the weekends rides.
Stu 👍🏻

**Comment by LTZGH** [comment]
Good luck.. And a pleasure.... Enjoy your rides...
